- 1.1.17
- _NAME: MX Master 4
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B04200000000
  _sensitive: {change-host: false, divert-keys: true, force-sensing: false, haptic-level: false, hires-scroll-mode: false, hires-smooth-invert: false, hires-smooth-resolution: false,
    reprogrammable-keys: true, scroll-ratchet: true, scroll-ratchet-torque: false, smart-shift: true, thumb-scroll-mode: false}
  _unitId: 98C5824E
  change-host: null
  divert-keys: {82: 1, 83: 1, 86: 1, 195: 1, 196: 1, 416: 1}
  dpi: 1000
  force-sensing: {0: 4577}
  haptic-level: 17
  hires-scroll-mode: true
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 195: 195, 196: 196, 416: 416}
  scroll-ratchet: 2
  scroll-ratchet-torque: 36
  smart-shift: 21
  thumb-scroll-invert: false
  thumb-scroll-mode: true
- _NAME: MX Master 4
  _sensitive: {hires-smooth-invert: true}
  _serial: 98C5824E
  _wpid: B042
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
